### PR TITLE
Smart updates fix

### LINKED ISSUE #212: add a default predicted release date for entries with no predictable date
### Describe your suggested feature

some way to choose a default frequency for all entries that doesn't have a predicted release date (even if it's completed (depending on the smart updates configuration))
the reason for the completed ones is that sometimes, the site will be marked as completed even though it isn't, which messes up smart updates.
### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.1](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by kana-shii**
Eventually closes #212 

I tried changing this line `.takeIf { status != SManga.COMPLETED.toLong() }` to make it interact with the smart updates option, but I wasn't able to figure out how. When I thought I was going to the right direction, it would give me a "Circular dependency" error.

### CODE REVIEW

**Comment by cuong-tran** [comment]
looks fine

File: app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt [hunk 1]
```diff
@@ -210,11 +212,15 @@ fun MangaActionRow(
...
+
+    val libraryPreferences: LibraryPreferences = Injekt.get()
+    val restrictions = libraryPreferences.autoUpdateMangaRestrictions().get()
+    val isSkipCompleted = MANGA_NON_COMPLETED !in restrictions
     val defaultActionButtonColor = MaterialTheme.colorScheme.onSurface.copy(alpha = DISABLED_ALPHA)
 
     // TODO: show something better when using custom interval
     val nextUpdateDays = remember(nextUpdate) {
-        return@remember if (nextUpdate != null) {
+        return@remember if (nextUpdate != null && isSkipCompleted) {
```
Comment (cuong-tran) [inline app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt:227]: if Skip is ticked, then this will make even other non-completed mangas will also not showing predicted time

Comment (kana-shii) [reply app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt:227]: I've just noticed that mb
but if I add || status != SManga.COMPLETED.toLong() to isSkipCompleted, I would have to add a status: Long,
but when I add it, it makes MangaScreen have errors
how would I fix it?
