### PR TITLE
Custom themes

### LINKED ISSUE #160: add Custom themes
### Describe your suggested feature

Basically a theme called custom theme which has an option linked to it called custom color picker
It's a feature from Kuukiyomi (Aniyomi fork)
A thing that would make this feature even better would be to be able to actually put the exact hex code that you want, while still having the color picker option. `(tried doing it but the app started crashing as soon as I clicked on the text camp)`
In Kuukiyomi, the only color you're able to pick is the main color.
The app itself will choose the secondary ones. It would also be really good if there was an option to pick them by yourself. `(kinda gave up on it because it chooses good secondary colors imo, but I could take a look into it later)`
A last thing that would be really good is if there was a way to actually save the custom themes and name them `(I don't even know where to start for this one tbh)`

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by kana-shii**
closes #160

### CODE REVIEW

File: app/src/main/java/eu/kanade/presentation/more/settings/widget/ThemeColorPickerWidget.kt [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+                ) {
+                    Button(
+                        onClick = {
+                            onItemClick(selectedColor, AppTheme.CUSTOM)
+                        },
+                        modifier = Modifier
+                            .fillMaxWidth()
+                            .height(48.dp),
+                        content = {
+                            Text("Confirm Color")
```
Comment (cuong-tran) [inline app/src/main/java/eu/kanade/presentation/more/settings/widget/ThemeColorPickerWidget.kt]: Move this text to i18n-kmk

**Comment by cuong-tran** [comment]
pls change its name to something cool
